### ISSUE TITLE
Did you end up solving issue? 

### ISSUE THREAD

**Issue by vxm5091** [febouge/elastic-nest-issue#1]
Hey, I came across the issue you submitted but couldn't find a follow-up on Discord. I'm bumping into the same error -- how did you end up fixing it? 

https://github.com/nestjs/elasticsearch/issues/794

**Comment by febouge** [comment]
Hi @vxm5091,

it was not really an issue. My MetricsModule was exporting just ElasticsearchService and it needs to export the entire ElasticsearchModule (only required if you want to use the service in other modules). Also, I removed the ElasticsearchService from the MetricsModule providers. It is not needed.

So, to sum up:

1. Export ElastisearchModule from your module if you needed (not just the service).
2. Remove ElasticsearchService from the providers definition. This line: https://github.com/febouge/elastic-nest-issue/blob/main/src/metrics/metrics.module.ts#L21

Hope it helps you!

**Comment by vxm5091** [comment]
Hey, sorry I didn't get back to you on this sooner. This was super helpful, thanks a lot!

**Comment by Erchoc** [comment]
please，how did you fix it?

**Comment by febouge** [comment]
Hi @Erchoc, it was not really an issue. You have the "solution" in https://github.com/febouge/elastic-nest-issue/issues/1#issuecomment-1171040310. 

It was just an export misconfiguration.
